CREATE TABLE IF NOT EXISTS "blog" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    "title" VARCHAR(128) NOT NULL,
    "description" VARCHAR(256) NOT NULL,
    "content" TEXT NOT NULL,
    "thumbnail" TEXT NULL DEFAULT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT "blog_id_pkey" PRIMARY KEY ("id")
);